version: '3'

services:
  api:
    image: api-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - "${API_PORT}:8080"
    volumes:
      - ./src:/usr/src/app/src
    environment:
      DB_URI: mongodb://db-dev:27017/main
      API_PORT: ${API_PORT}
      SECRET_KEY: ${SECRET_KEY}

  db:
    container_name: db-dev
    image: mongo:4.0-xenial
    restart: always
    ports:
      - "${DB_PORT}:27017"
    volumes:
      - ./data:/data/db
